### ISSUE TITLE
Split Interval into separate package?

### ISSUE THREAD

**Issue by ssfrr** [mbauman/AxisArrays.jl#20] opened 2015-09-13 15:34 UTC
As you mention in JuliaLang/julia#12624, several people have implemented interval types in their packages. I know at least of @dcjones's [IntervalTree](https://github.com/BioJulia/IntervalTrees.jl) package. I'm also looking at intervals for a package that I'm working on. Would you be interested in splitting out the interval type into a separate package? It seems like your implementation is useful pretty generally.

**Comment by mbauman** [comment] 2015-09-13 20:07
Perhaps.  I'm still not entirely happy with how they behave, and I've slowly been tinkering with their definition (I'll probably propose something along these lines soon: https://github.com/mbauman/AxisArrays.jl/compare/repeatedintervals).

There are two ways to define intervals, and I don't think there's one correct answer here, so I hesitate to grab the Intervals.jl name.

I've made them kinda-sorta Range-like, where they can feasibly support any ordinal type.  They're not subtypes of Number, so they don't really act like true numbers.  I've just defined a few arithmetic operations that I need for this package and kept things relatively simple.  The other trick is that I want to *delay* some operations until I use them in indexing to avoid fencepost and numerical accuracy problems.  This probably isn't going to be a common concern in other domains.

The other option is to only allow intervals between `Number`s, and intervals themselves a subtype of `Number`.  This allows them to be used much more extensively as a computational type.  This is what @dpsanders' [ValidatedNumerics.jl](https://github.com/dpsanders/ValidatedNumerics.jl) package does.

**Comment by ssfrr** [comment] 2015-09-14 20:44
My use case is pretty straightforward and I think pretty similar to your needs. I'm working on some common types for DSP (streams, buffers, processing nodes) and just want to use SIUnit-valued intervals for indexing multi-channel, uniformly-sampled signals in the time or frequency domain. I haven't thought through the semantics fully yet, and at first will probably just quantize the given interval endpoints to the nearest sample values. It's mostly a convenience so you can say "give me the first 500ms of audio from this buffer"

I'm definitely not familiar enough with interval arithmetic to evaluate which semantics are more generally useful, but do you think that the common core of a parameterized tuple (maybe with the `A..B` operator) could serve as a common-enough scaffold that it could be shared and extended by other packages?

I could just write some `getindex` handlers that take 2tuples, or cut-paste one of the other Interval implementations, but it seems like they're used in enough places that it might be useful to have the basics shared.

I could just be overthinking it though, and would definitely defer to your expertise here.

**Comment by mbauman** [comment] 2015-09-14 22:13
> It's mostly a convenience so you can say "give me the first 500ms of audio from this buffer"

Oh man, yes, that's exactly what I want to express, too.

I definitely think we can work towards a registered Intervals package.  In order to do so, I'd like to see if we can get a consensus from all the Interval stake-holders around here on a package name, home, and behavior.  Ideally, we'd all manage to find some implementation that most of us are happy with and can use in our respective packages.

Here are the important parts that I'd like to have in an intervals implementation:
* It's an immutable type that has two concretely-typed fields of the same type, `lo` and `hi` (actual field names are irrelevant).
* It should be able to support types that are `Number` or `AbstractTime`.  Maybe more, too, but at least those.
* It *isn't* itself a subtype of `Number`.  This is somewhat negotiable, but I've found that this makes life a lot easier.  See: [this comment](https://github.com/mbauman/AxisArrays.jl/blob/e27bc5342a7d66c345ca491ac831ab1781730300/src/intervals.jl#L55-L77) for details.
* A non-interval `x` can convert to an interval with `lo == hi == x`.
* Basic arithmetic and comparisons are implemented in a consistent manner, allowing *both* homogenous arithmetic/comparison (between two Intervals) and heterogeneous arithmetic/comparison (an Interval against a "scalar", via promotion).

An implementation I'm fairly happy about is at https://github.com/mbauman/AxisArrays.jl/blob/e27bc5342a7d66c345ca491ac831ab1781730300/src/intervals.jl#L1-L115, but this certainly isn't the way it must be.

On the Intervals-as-computable-numbers front, there's:
* @dpsanders' [ValidatedNumerics.jl](https://github.com/dpsanders/ValidatedNumerics.jl): `Interval{T<:Real} <: Real`. Only supports Real numbers, and is itself Real.  Uses careful rounding modes to guarantee that the result is within the interval, and is carefully designed to deal with floating point inaccuracies.  I'm afraid that our use-cases don't line up.  Do you mind if we register a general-purpose package called `Intervals.jl`?
* @andrioni's [Intervals.jl](https://github.com/andrioni/Intervals.jl): `Interval{T<:Union(Float32, Float64, BigFloat)} <: Number`. This interfaces with MPFI, and probably can't use a shared Interval type.  Would you feel pushed aside if we registered a package called `Intervals.jl`?

On the Intervals-as-storage-type-with-limited-computation front, there's:
* AxisArray's `Interval{T<:Union{Number, AbstractTime}}`
* @sjkelly's [Intervals.jl](https://github.com/sjkelly/Intervals.jl): `Interval{T} <: AbstractInterval{T}`. I think your current work is fairly consistent with what I'm proposing, but I'd like to extend it with the `..` operator and arithmetic/comparisons with scalars.  Would you be interested in collaborating?  Would you like to host or officially maintain the result?  Or would you prefer this to be a separate work?
* @scheinerman's [ClosedIntervals.jl](https://github.com/scheinerman/ClosedIntervals.jl): `ClosedInterval{T<:Real}`. Would you be interested in the above definitions?  Your work is a little farther from what I have proposed, but we may be able to find some middle ground.

And then there are a bunch of domain-specific implementations that may not get any advantages from a common package:
* @zenna's [AbstractDomains.jl](https://github.com/zenna/AbstractDomains.jl): `Interval{T<:Real} <: Domain{T}`
* @TheBB's [NURBS.jl](https://github.com/TheBB/NURBS.jl): `Interval{T<:Real}`
* @dlfivefifty's [ApproxFun.jl](https://github.com/ApproxFun/ApproxFun.jl): `Interval{T} <: IntervalDomain{T}`
* @dcjones' [BioJulia/IntervalTrees.jl](https://github.com/BioJulia/IntervalTrees.jl): `immutable Interval{T} <: AbstractInterval{T}`

Y'all are welcome to join in - what do you think about an officially registered Intervals package?

**Comment by dlfivefifty** [comment] 2015-09-14 22:25
ApproxFun’s Interval is a subtype of Domain.  Other Domains include Circles, Arcs, etc.  So I could only imagine ApproxFun taking advantage of a common package if the package was more general: “Domains.jl” or “Sets.jl”.

	This may be worthwhile for interval arithmetic for Complex numbers, where you want to work with "Disk"s, not “Interval”s.

**Comment by sjkelly** [comment] 2015-09-14 22:57
@mbauman @ssfrr I'm up for extending Intervals.jl however needed and maintaining forward compatibility. My initial motivation was to use it as a rigorous basis for HyperRectangles and DistanceFields. I have moved the package to JuliaGeometry so collaboration will be easier. I really like your Interval implementation, especially the `..` notation! 

@dpsanders and I talked about JuliaCon and IIRC my arithmetic implementations are not congruent with the IEEE proposal. It might take some time to integrate with the needs of ValidatedNumerics, but it doesn't seem impossible.

**Comment by ssfrr** [comment] 2015-09-14 23:42
One thing to consider with the `A..B` syntax is that it may get used for the non-overloadable `getfield`, so that syntax might become unavailable. Also the precedence is rather low, so currently `1..4 + 7..1` doesn't do what you'd want. I think that with a consensus of a few people though it's a lot easier to get that sort of thing changed (or a new operator added to the parser).

**Comment by zenna** [comment] 2015-09-14 23:54
I think:

- Intervals are a kind of set and it makes sense for them to be a subtype of sets hence `Domain{T}` in AbstractDomains.
- When you take this perspective some operations such as `X = Interval(0,1); X>0.5` have multiple, natural answers.  Natural because it's a set operation; the answer should be a set.  Multiple because it depends on what domain you want the answer to be in.
- Interval bounds (closed vs open) should be explicit (I haven't done this in Abstract Domains).  Possibly it could be done with no cost using types.
- Intervals being a subtype of `Number` has slightly more pros than cons.  Fundamentally, they do not fit into the type-hierarchy.   OTOH there is a lot of existing code designed for numbers that we would like to be able to use with intervals.
- Interval arithmetic is more useful when you can go both forwards and backwards.  Otherwise you will get overapproximation errors which renders it useless for complicated functions.

**Comment by dlfivefifty** [comment] 2015-09-15 01:40
AbstractDomains.jl seems very useful for ApproxFun.  I’d be in favour of using that as the base for “Interval”, and happy to contribute.  

Zenna: Either way, maybe I should at some point port ApproxFun’s lists of domains ("Circle", "Disk”, “Line”, “Ray”, “Arc”) over to AbstractDomains.jl?

**Comment by mbauman** [comment] 2015-09-15 13:20
Wow, this is great everyone.  Thanks for the feedback and being so willing to collaborate!

My use case is very pragmatic — I just want intervals to make an API simpler. If being part of a larger InfiniteSet/Domain hierarchy means that more of us can work together then I'm all for it.

Some specific responses:

> @ssfrr One thing to consider with the A..B syntax is that it may get used for the non-overloadable getfield, so that syntax might become unavailable

One of my goals is to present a strong case for an alternative… and make sure that it doesn't get wasted on a rarely used syntax.  I don't mind the low precedence all that much — it behaves like `:`, which has some nice qualities once you get used to it.

@zenna - AbstractDomains.jl is much more general that I had first thought.  I agree that it could make for a great basis here.

> some operations such as X = Interval(0,1); X>0.5 have multiple, natural answers. Natural because it's a set operation; the answer should be a set. Multiple because it depends on what domain you want the answer to be in.

I disagree on this point.  I think that the comparison operators in base should always return a `Bool`, which limits the choices we can make.  In that vein, I think the base comparison operators should behave as though they were ∀ numbers in the interval/domain.  This has some very cool advantages:

```jl
julia> r = cumsum(rand(100));

julia> idxs = searchsorted(r, 5..8) # With AxisArray's intervals
12:17

julia> r[idxs]
6-element Array{Float64,1}:
 5.43329
 6.04483
 6.07484
 6.68762
 7.47311
 7.85931
```

> Interval bounds (closed vs open) should be explicit

I wouldn't be against supporting it, but for Intervals I'd prefer a closed default.

> Intervals being a subtype of Number has slightly more pros than cons.

My two biggest cons are that I really want the ability to form intervals between dates/DateTime (`today()-Day(5) .. today()`) and that it causes ambiguities with every other Number wrapper that is also a Number (DualNumbers, SIUnits, ForwardDiffNumbers, Compose measurements, and so on).  For each of these that you'd like to interoperate with, you need to explicitly choose who wins in a promotion or get tons of ambiguity warnings.  But I do understand that this does make the type much more powerful for general use.  Maybe someday we'll get ambiguity warnings deferred to runtime errors, which would make this more amenable.

If `Interval{T<:Number} <: Number`, then perhaps we could also use the `..` operator to form a `TimeInterval{T<:AbstractTime}` (like how `:` forms different kinds of ranges).  It'd mean a lot of code duplication, but it's one solution.  But since we don't have multiple inheritance, it may be tough to have all `Domain`s also be a subtype of Number, so this may be limited by that in any case.

> Interval arithmetic is more useful when you can go both forwards and backwards

I'm afraid I don't understand what you mean by this, could you explain a little further?

**Comment by ssfrr** [comment] 2015-09-15 16:05
I wonder if the split is that:
1. Intervals can be used to represent uncertainty, where you want to start with bounds on your inputs and define operations that propagate that uncertainty (preferably keeping the bounds tight). From this perspective the answer to `4 < 3..5` is the set `{true, false}`, as is `3..5 == 3..5` as in AbstractDomains. In general operations are defined as if you're doing the operation elementwise on the cartesian product and then returning the Interval bounding the results.
2. Intervals can be used to represent known contiguous spans in a domain. From this perspective `4 < 3..5` is `false` and `3..5 == 3..5` is `true`. It's not as clear to me that most arithmetic operations make sense here, though maybe I'm thinking too narrowly. Set operations like union and intersection seem to make sense, though I'm not sure what the union of disjoint intervals should be.

Just to throw the idea out there, if there isn't enough common ground for these to be represented with the same underlying type I wonder if `Interval` and `Span` could represent the two cases? I do think it's better if we can find a common basic type though.

@mbauman would you mind giving a concrete example of where ambiguity warnings pop up with `Interval <: Number` and not otherwise?

**Comment by mbauman** [comment] 2015-09-15 16:25
> would you mind giving a concrete example of where ambiguity warnings pop up with Interval <: Number and not otherwise?

Sure.  On a hand-wavy level: Is `(1..2)*Second` an `SIQuantity{Interval}` ((1 to 2) seconds) or is it an `Interval{SIQuantity}` (1 second to two seconds)?  Julia needs to be told what to do in each and every case you want to support.  And even in cases you don't care to support, it will complain loudly.

On a concrete level: You hit ambiguities in `promote_rule` and any non-promoting operators you both want to support, like comparison operators and (IIRC) array arithmetic, because you both want to define:

`f(::Number, ::Interval) = …`
`f(::Interval, ::Number) = …`
`f(::SIQuantity, ::Number) = …`
`f(::Number, ::SIQuantity) = …`

This is ambiguous for the case `f(::Interval, ::SIUnit)` since they're both Number.  `Base.promote_rule` is even trickier, since it can effectively hide the ambiguities since it tries things in both orders for you, and can surprisingly return `Any` in ambiguous combinations without warning.  If Interval isn't a Number, then it doesn't match in the SIUnit definitions and there is no ambiguity.

**Comment by dlfivefifty** [comment] 2015-09-15 20:23
For the question about disjoint intervals: ApproxFun has a type UnionDomain that has a Vector of subdomains, which can be of different types.

**Comment by JeffBezanson** [comment] 2016-07-26 20:15
+1. I'll also put in a vote for @mbauman -style intervals (where they are not Numbers, and act mostly like sets). It would be good to have a standard type for expressing range queries.

**Comment by dpsanders** [comment] 2016-07-26 20:37
In ValidatedNumerics.jl, the fact that `Interval`s "are numbers" (i.e. have a number-type trait, which currently must be expressed as `Interval <: Real`) is important. Having said that, maybe it would not be *too* much work to get rid of this (though I distinctly remember that there is always a crucial moment when it is much more natural to have it).

I would propose that the simple interval type under discussion in this issue could be called literally a `SimpleInterval`.

**Comment by dpsanders** [comment] 2016-07-26 20:37
cc @timholy, who also asked me about this at JuliaCon.

**Comment by JeffBezanson** [comment] 2016-07-26 20:57
Intervals for numerical analysis seem to be a fairly special and separate case. There you definitely want to be able to use them as numbers. For indexing all we really need is a representation of the predicate `x->lo<=x<=hi`.

**Comment by dlfivefifty** [comment] 2016-07-26 21:10
In ApproxFun, `Interval` is a set, not a number.  I think `Interval <: Number` is unintuitive, even in the context of a interval arithmetic (where it is still a set).

**Comment by dlfivefifty** [comment] 2016-07-26 21:13
Maybe `Number` should be added as an [interface](http://docs.julialang.org/en/release-0.4/manual/interfaces/), to describe what is assumed to be overriden (+,-,*,/,etc.), and what behaviour is expected (associativity?).

**Comment by dpsanders** [comment] 2016-07-26 21:15
`Interval <: Number` is indeed just a convenience, which gets around exactly the current lack of interfaces / traits in Julia. Doing this significantly reduces the number of functions, conversions, etc. that must be defined. 

Intervals are sets, but we want to be able to do arithmetic on them, which is why they are "sort of numbers".

**Comment by dpsanders** [comment] 2016-07-26 21:17
It would definitely be useful to codify which functions should be defined for new number types. E.g. to define `exp` of a complex interval, it was necessary to define (IIRC) `isnan`, etc.

**Comment by JeffBezanson** [comment] 2016-07-26 21:18
Maybe there could be an underlying `Interval` type with a minimal set-like interpretation, that can be wrapped in a type that's a subtype of Number for doing arithmetic.

**Comment by dlfivefifty** [comment] 2016-07-26 21:31
But `Interval <: Number` only makes sense if `Vector <: Number` also makes sense, as `Interval` is the continuum limit of a `Vector`.

**Comment by dlfivefifty** [comment] 2016-07-26 21:33
Maybe that's not quite accurate since `getindex` is not defined...but in some sense `Interval(0,1)` is the same as `0:dx:1`

**Comment by timholy** [comment] 2016-07-26 21:57
I remain hopeful about this, but I recognize there may be a diversity of wants here.

The things I want in a minimalist Interval package:
- the notion of a 1d continuous set, i.e., `Range`-without-`step`
- construction with the syntax `lo..hi`
- the ability to express an *empty* interval when `lo>hi` (much as we do for Ranges). For use as a representation of a set, the ability to construct something that's empty is pretty important. (Note that `lo..lo` is not empty, it has a single point in it.)

The last point might be the sticking point. From a brief survey, much of the interval-mathematics makes liberal use of `min` and `max`; to make these compatible, I think we'd need to introduce a notion of monotonic functions (both flavors, increasing and decreasing), and throw an error for applying a non-monotonic function on an `Interval`. In a sense I think that's a good idea anyway, since if your function isn't monotonic then you can no longer compute the output interval just in terms of the interval's endpoints.

Finally, I'll point out that one model for how to handle this might be `ColorTypes` vs `ColorVectorSpace`. The former implements minimalist types, and the latter extends it to introduce mathematical operations for some of those types (`Gray`, `AbstractRGB`, and their variants with alpha channel) that are widespread in image processing but which are not actually correct from the standpoint of rigorous colorimetry. Purists should not say `using ColorVectorSpace`, but people who want high-performance image processing should.

**Comment by dlfivefifty** [comment] 2016-07-26 21:59
Can I add a bullet point:

* Support complex numbers (intervals in the complex plane)

**Comment by timholy** [comment] 2016-07-26 22:01
What do you mean by that?
- A 1d interval: numbers along the line between two points
- A 2d interval: a box-shaped region

**Comment by dlfivefifty** [comment] 2016-07-26 22:02
• A complex interval: numbers along the line between two complex points

**Comment by timholy** [comment] 2016-07-26 22:13
The problem is desirable properties from one might conflict with desirable properties from the other. Thinking of them as simple sets, you'd like to say that a number `x` is in the interval if `lo <= x <= hi`. This requires nothing but an ordering of the numbers, but of course complex numbers don't have a generic ordering defined. So that definition would exclude the property you want.

Your version uses a different definition: `x` is in the set if there exists an `s` satisfying `0 <= s <= 1` such that `x == s*lo + (1-s)*hi`. This requires that the numbers live in a vector space. If you think about it, this definition also excludes my 3rd desirable property (the ability to construct an empty interval).

**Comment by dlfivefifty** [comment] 2016-07-26 22:21
For me, the utility of `Interval` is to represent a special set, along with `Circle`, `Disk`, `Triangle`, `Ray`, `Line`, `EmptySet`, etc.  

However, complex intervals are not useful for in the context of interval arithmetic.

I think if there is going to be a common `Intervals.jl` package, it should encapsulate both the set viewpoint and the interval arithmetic viewpoint.  Otherwise, there are still going to be multiple implementations of `Interval`.  

Though maybe there is not enough common ground to do this.

**Comment by timholy** [comment] 2016-07-27 01:03
I think you're asking for something that's very different from what (I think) the rest of us are discussing. These should be separate packages. The `Intervals` I'm envisioning would probably be <20loc, and wouldn't serve your purposes at all.

**Comment by dlfivefifty** [comment] 2016-07-27 01:09
My usage is the same as @zenna's AbstractDomains.jl, so its not just me.

**Comment by dlfivefifty** [comment] 2016-07-27 01:12
Though I'm happy with it being a separate package: in the set setting, one may also want to have types to represent open/closed intervals: `(-1,1)`, `(-1,1]`, `[-1,1)`, `[-1,1]` which would make things too complicated.

**Comment by scheinerman** [comment] 2016-07-27 13:02
Hi all,

One comment on Interval <: Number ... I don't care for this. I think what would be better is for there to be an AbstractSet type of which Set, IntSet, and Interval would be subtypes. The only issue there is that the union of intervals is typically not an interval.

I'm pretty satisfied with the approach I've taken in my ClosedIntervals module available here: https://github.com/scheinerman/ClosedIntervals.jl.git

-Ed

**Comment by timholy** [comment] 2016-07-27 13:56
Yes, ClosedIntervals looks much like what I was intending. Personally I wouldn't have auto-swapped the constructor arguments, and just encoded an empty as `R<L`. (Note that the UnitRange constructor does not auto-swap the arguments in 5:2.) If we could also add `..` as a constructor and `show` syntax, that looks like the package I was hoping for.

**Comment by dlfivefifty** [comment] 2016-07-27 20:59
And it can be made to work with Complexs 😛
```julia
ClosedInterval(l::Complex,r::Complex) = ClosedInterval(l,r,false)
ClosedInterval(1.0+0.0im,1+2.0im)
```
I'd suggest that it might be better to not override `Base.length`:  it usually denotes the number of elements in an iterator.  In ApproxFun, I changed the `length` to `arclength` to avoid some issues this created.

**Comment by timholy** [comment] 2016-09-10 09:21
Closed by https://github.com/JuliaMath/IntervalSets.jl

**Closed by timholy** 2016-09-10 09:21 UTC
